# Generated by Django 5.1.4 on 2024-12-21 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='listing_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('despcription', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='comment_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('user_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsbyuser', to=settings.AUTH_USER_MODEL)),
                ('listing_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsinlisting', to='auctions.listing_model')),
            ],
        ),
        migrations.CreateModel(
            name='bid_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('user_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidsbyuser', to=settings.AUTH_USER_MODEL)),
                ('listing_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidsinlisting', to='auctions.listing_model')),
            ],
        ),
    ]
