# Generated by Django 5.1.4 on 2024-12-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_despcription_listing_model_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_model',
            name='image_url',
            field=models.URLField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vecteezy.com%2Ffree-vector%2Fdefault-user&psig=AOvVaw0ewbOckAGX94wQkydvuwY6&ust=1734877699083000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCJi-zJmJuYoDFQAAAAAdAAAAABAE'),
        ),
    ]
