# Generated by Django 5.1.4 on 2024-12-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_model_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='usersinwatchlist', to='auctions.listing_model'),
        ),
    ]
