# Generated by Django 5.1.4 on 2024-12-21 18:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_model',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
