# Generated by Django 5.1.4 on 2024-12-22 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_user_mylistings_alter_listing_model_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mylistings',
        ),
        migrations.AddField(
            model_name='listing_model',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mylistings', to=settings.AUTH_USER_MODEL),
        ),
    ]
