# Generated by Django 5.1.4 on 2024-12-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_user_mylistings_listing_model_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_model',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing_model',
            name='starting_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
