# Generated by Django 5.1.4 on 2024-12-22 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_model_is_closed_listing_model_starting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_model',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings_i_won', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing_model',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mylistings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing_model',
            name='starting_price',
            field=models.IntegerField(),
        ),
    ]
