# Generated by Django 5.1.4 on 2024-12-22 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_model_winner_alter_listing_model_createdby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing_model',
            name='winner',
        ),
    ]
